### ISSUE TITLE
"IOError: [Errno 13] Permission denied" on Windows

### ISSUE THREAD

**Issue by mitchcurtis** [mitchcurtis/inkscape-9-patch-export#1]
> Traceback (most recent call last):
>   File "export_9_patch.py", line 142, in <module>
>     _main()
>   File "export_9_patch.py", line 138, in _main
>     e.affect()
>   File "C:\Program Files\Inkscape\share\extensions/inkex.py", line 283, in affect
>     self.effect()
>   File "export_9_patch.py", line 54, in effect
>     self.exportLayers(layerDestSvgPath, showLayerIds)
>   File "export_9_patch.py", line 74, in exportLayers
>     doc.write(dest)
>   File "src/lxml/lxml.etree.pyx", line 2048, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:65694)
>   File "src/lxml/serializer.pxi", line 717, in lxml.etree._tofilelike (src/lxml/lxml.etree.c:139599)
>   File "src/lxml/serializer.pxi", line 776, in lxml.etree._create_output_buffer (src/lxml/lxml.etree.c:140263)
>   File "src/lxml/serializer.pxi", line 765, in lxml.etree._create_output_buffer (src/lxml/lxml.etree.c:140063)
> IOError: [Errno 13] Permission denied

Notes:
- http://wiki.inkscape.org/wiki/index.php/Python_modules_for_extensions#The_Effect_class says document is a "DOM document, as a lxml.etree".
- http://lxml.de/api/lxml.etree._ElementTree-class.html#write
- https://docs.python.org/2/library/tempfile.html says: "Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later)."

**Comment by mitchcurtis** [comment]
Potential fix: https://stackoverflow.com/a/15235559/904422
Discussion of limitation: https://bugs.python.org/issue14243#msg164504
